# Generated by Django 4.2.2 on 2023-10-03 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_previewmodel_related_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagemodel',
            options={'verbose_name': 'image', 'verbose_name_plural': 'images'},
        ),
    ]
