# Generated by Django 4.2.2 on 2023-07-11 15:31

from django.db import migrations, models
import django.db.models.deletion
import image.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('description', models.TextField(max_length=4000)),
                ('designer_name', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='PreviewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview', models.ImageField(upload_to=image.models.upload_to_preview)),
                ('related_progect', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preview', to='image.projectmodel')),
            ],
            options={
                'verbose_name': 'preview',
                'verbose_name_plural': 'previews',
            },
        ),
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_link', models.ImageField(upload_to=image.models.upload_to_image)),
                ('related_progect', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='image.projectmodel')),
            ],
            options={
                'verbose_name': 'image',
                'verbose_name_plural': 'images',
            },
        ),
    ]
