# Generated by Django 4.2.2 on 2023-07-13 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='previewmodel',
            old_name='related_progect',
            new_name='related_project',
        ),
    ]
