# Generated by Django 4.2.2 on 2023-07-13 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_rename_related_progect_previewmodel_related_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previewmodel',
            name='related_project',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_preview', to='image.projectmodel'),
        ),
    ]
