# Generated by Django 4.2.2 on 2023-07-17 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0003_alter_previewmodel_related_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagemodel',
            old_name='related_progect',
            new_name='related_project',
        ),
    ]
